README.md, pom.xml
N/A
Documentation
There is no information about building this project
There is a README.md file that explains how to build the project
(if any of the questions/checkboxes don't …
=> Add a README.md file to explain how to build the project

pom.xml
Report some modification in the pom.xml to report configuration of powsybl-core
It works
It still works
(if any of the questions/checkboxes don't apply, please delete them …
=> Fix pom configuration

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare release 2.6.0

distribution-hpc/pom.xml
N/A
Detail
The `computation-slurm` module is referenced in the distribution-hpc pom.xml file as an external dependency.
The dependency is now fixed
(if any of the …
=> Fix distribution dependencies

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
Prepare release v2.6.1
- Fix UnsatisfiedLinkError in MPI
- Fix distribution-hpc pom.xml file
=> Prepare release v2.6.1

computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationManager.java
#10 
Bug fix
It takes too much time for query in production environment.
With --help, it does not query slurm's database.
(if any of the questions/checkboxes don't apply, please …
=> Use sacct --help to check.

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare release 2.8.0

.travis.yml, appveyor.yml
=> Shallow clone powsybl-core

computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmUnitTests.java
Assertion should be on main thread.
Fix unit tests. The assertion should be in main thread, not in execution's thread.
(if any …
=> Fix unit test

computation-slurm-test/pom.xml, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/AbstractReturnOKExecutionHandler.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmCancelExectuionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmCancelExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmIntegrationTests.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmInvalidExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmNormalExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmOtherCaseTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmUnitTests.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationManager.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandExecutionsTestFactory.java, pom.xml
=> Split tests

.github/workflows/maven.yml, distribution-hpc/pom.xml, pom.xml
Coverage systematically appears as 0% in sonar.
Correct coverage is displayed.
=> Fix tests coverage display in sonar

computation-slurm/pom.xml, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationManager.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmConstants.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmStatusManager.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SlurmComputationManagerTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SlurmStatusManagerTest.java
=> Code coverage

distribution-hpc/pom.xml, pom.xml
Signed-off-by: Sylvain Leclerc <sylvain.leclerc@rte-france.com>
Powsybl version update.
=> Update powsybl-parent version to v2, powsybl-core version to 3.2.0.

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare release 2.9.0

computation-slurm-test/src/test/java/com/powsybl/computation/slurm/AbstractIntegrationTests.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmCancelExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmInvalidExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmNormalExecutionTest.java, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmOtherCaseTest.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/AbstractTask.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/CommandUtils.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/FlagFilesMonitor.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/JobArraySlurmTask.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchCmdBuilder.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchScriptGenerator.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmArrayJobTask.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationConfig.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationManager.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmTaskImpl.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandExecutionsTestFactory.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandResultTestFactory.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/DefaultSlurmTaskTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/JobArraySlurmTaskTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchCmdTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchScriptGeneratorTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SlurmArrayJobTaskTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SlurmComputationConfigTest.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SlurmTaskTest.java, computation-slurm/src/test/resources/expectedShell/group3.batch, computation-slurm/src/test/resources/expectedShell/myEchoSimpleCmdWithUnzipZip.batch, computation-slurm/src/test/resources/expectedShell/simpleCmdWithCount3.batch
Parser non-zero line to error.
=> Add array_job.

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
Powsybl-core dependency update and powsybl hpc release.
=> Prepare release v2.10.0

computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmNormalExecutionTest.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/CommandUtils.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchScriptGenerator.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandExecutionsTestFactory.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchScriptGeneratorTest.java, computation-slurm/src/test/resources/expectedShell/argsWithSpaces.batch, computation-slurm/src/test/resources/expectedShell/group3.batch, computation-slurm/src/test/resources/expectedShell/myEchoSimpleCmdWithUnzipZip.batch
=> Fix_bug:Escape spaces in arg

computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmNormalExecutionTest.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchScriptGenerator.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandExecutionsTestFactory.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchScriptGeneratorTest.java, computation-slurm/src/test/resources/expectedShell/myEchoSimpleCmdWithUnzipZip.batch
=> Fix spaces in files

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm-test/src/test/java/com/powsybl/computation/slurm/SlurmNormalExecutionTest.java, computation-slurm/pom.xml, computation-slurm/src/main/java/com/powsybl/computation/slurm/CommandUtils.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchScriptGenerator.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/CommandExecutionsTestFactory.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchScriptGeneratorTest.java, computation-slurm/src/test/resources/expectedShell/argsWithSpaces.batch, computation-slurm/src/test/resources/expectedShell/group3.batch, computation-slurm/src/test/resources/expectedShell/myEchoSimpleCmdWithUnzipZip.batch, distribution-hpc/pom.xml, pom.xml
=> Prepare v2.10.1

computation-slurm/src/main/java/com/powsybl/computation/slurm/AbstractTask.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/JobArraySlurmTask.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchScriptGenerator.java, computation-slurm/src/test/java/com/powsybl/computation/slurm/SbatchScriptGeneratorTest.java, computation-slurm/src/test/resources/expectedShell/argsWithSpaces.batch, computation-slurm/src/test/resources/expectedShell/group3.batch, computation-slurm/src/test/resources/expectedShell/myEchoSimpleCmdWithUnzipZip.batch, computation-slurm/src/test/resources/expectedShell/simpleCmdWithCount3.batch
=> Fix flag monitor detect the last array job done.

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
N/A
Dependency update
Current release is based on powsybl-core v3.3.0 and powsybl-parent v2
Prepare next release based on powsybl-core v3.7.1 and powsybl-parent v3
(if any of the …
=> Prepare release 2.11

pom.xml
Signed-off-by: Sylvain Leclerc <sylvain.leclerc@rte-france.com>
Dependencies bump / vulnerabilities fixing
=> Bump powsybl-core to v4.1.2, and import its dependency management

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare v2.11.1

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Release v2.12.0

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
**_RELEASE PR - DO NOT MERGE ON GITHUB_**
=> Prepare release v3.0.0

pom.xml
No
Update
powsyblcore 6.4.0
powsyblcore 6.4.1
=> Update powsybl-core to 6.4.1

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare release 3.1.0

pom.xml
No
Dependency upgrade
Core 6.4.1
Core 6.5.0
=> Update powsybl-core to 6.5.0

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
**DO NOT SQUASH-MERGE THIS PR**
=> Prepare release 3.2.0

pom.xml
=> Update powsybl-core to v6.6.0 and powsybl-parent to v20

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
=> Prepare release v3.3.0

pom.xml
No
Dependency update
- powsybl-core v6.6.0
- jsch v0.2.21
- logback v1.5.12
- powsybl-core v6.7.0
- jsc v0.2.24
- logback v1.5.14
=> Update powsybl-core dependency to v6.7.0 and other dependencies

computation-mpi/pom.xml, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
**Do not merge on GitHub!**
No
Release
v3.4.0-SNAPSHOT
v3.4.0 and v3.5.0-SNAPSHOT
=> Prepare release v3.4.0

computation-mpi/src/main/java/com/powsybl/computation/mpi/MpiComputationManager.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SbatchCmdBuilder.java, computation-slurm/src/main/java/com/powsybl/computation/slurm/SlurmComputationParameters.java, pom.xml
No
Dependency update
Uses `javax.annotation`
HPC uses powsybl-core 6.7
Replaced `javax.annotation` annotations with `org.jspecify` equivalents to maintain annotation consistency across the codebase.
HPC uses powsybl-core 6.8
=> Update to powsybl-core 6.8.0-RC2

pom.xml
No
Dependencies update
- Uses powsybl-core 6.8.0-RC2
- Old deps
- Uses powsybl-core **6.8.0**
- New deps
| Library / component | Previous version | New version | PR |
| --- | --- | --- | --- |
| commons-exec | 1.4.0 | 1.5.0 | #98 |
| jsch | 0.2.24 | 2.27.2 | #98 |
| junit-jupiter | …
=> Update powsybl-core to v6.8.0 and other dependencies

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
No
update
Builds fail on macOS-15 when using maven wrapper v3.2.0
```
Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised.
Investigate or delete /Users/runner/work/powsybl-hpc/powsybl-hpc/.mvn/wrapper/maven-wrapper.jar to attempt a clean download.
If you updated your Maven version, you need to update the specified wrapperSha256Sum property.
Error: Process completed with exit code 1.
```
Maven wrapper is updated to v3.3.3 and the builds work
**Does this PR introduce a breaking change or deprecate …
=> Update maven wrapper

.github/workflows/maven.yml, .github/workflows/snapshot-ci.yml, computation-mpi/pom.xml, computation-mpi/src/main/java/com/powsybl/computation/mpi/MpiComputationManager.java, computation-slurm-test/pom.xml, computation-slurm/pom.xml, distribution-hpc/pom.xml, pom.xml
No
Java update
Uses java 17
Uses Java 21
PowSyBl-HPC now only supports Java 21 and higher. Please check that your installed SDK is still compatible. If you are using Ubuntu 20.04 LTS and the preinstalled Maven version, you will need to upgrade your Maven version too at least up to a version 3.9.x.
**Other …
=> Migrate to Java 21 + update CI actions
